FROM       registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
WORKDIR /app
COPY demo-0.0.1-SNAPSHOT-jar-with-dependencies.jar /app
CMD ["java", "-jar", "/app/demo-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]
